version: '3.9'

services:
  quarkus-petclinic-native:
    # Build the native image first with the following command: mvn -P native -DskipTests package
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.fast-jar
    image: quarkus-petclinic-native:latest
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://quarkus-petclinic-db:5432/mydb
      - QUARKUS_DATASOURCE_USERNAME=developer
      - QUARKUS_DATASOURCE_PASSWORD=developer
      - KEYCLOAK_URL=http://keycloak-petclinic:8080
      - KEYCLOAK_REALM=quarkus
      - KEYCLOAK_CLIENT_SECRET=secret
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      quarkus-petclinic-db:
        condition: service_healthy
      keycloak-petclinic:
        condition: service_started
    networks:
      - petclinic

  quarkus-petclinic-db:
    image: "postgres:14"
    mem_limit: 128m
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=developer
      - POSTGRES_DB=mydb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname $$POSTGRES_DB --username $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 6
    ports:
      - "5432:5432"
    networks:
      - petclinic

  keycloak-postgres-db:
    image: postgres:14
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak_db
    ports:
      - "5433:5432"
    networks:
        - petclinic

  keycloak-petclinic:
    image: jboss/keycloak:latest
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloak-postgres-db
      DB_DATABASE: keycloak_db
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm-export.json
      KEYCLOAK_USER_REGISTRATION: true
      KEYCLOAK_REALM: quarkus
    volumes:
      - ./keycloak-data:/opt/jboss/keycloak/standalone/data
    ports:
      - "8081:8080"
    depends_on:
      - keycloak-postgres-db
    networks:
        - petclinic

networks:
  petclinic:
    driver: bridge

