apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak-postgres-db
  name: keycloak-postgres-db
  namespace: default
spec:
  ports:
    - name: "5433"
      port: 5433
      targetPort: 5432
  selector:
    io.kompose.service: keycloak-postgres-db
status:
  loadBalancer: {}
