apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: quarkus-petclinic-db
  name: quarkus-petclinic-db
  namespace: thebigsasha-bcexam-dev
spec:
  replicas: 1
  selector:
    io.kompose.service: quarkus-petclinic-db
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/quarkus-petclinic-petclinic: "true"
        io.kompose.service: quarkus-petclinic-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: mydb
            - name: POSTGRES_PASSWORD
              value: developer
            - name: POSTGRES_USER
              value: developer
          image: ' '
          livenessProbe:
            exec:
              command:
                - pg_isready --dbname $POSTGRES_DB --username $POSTGRES_USER
            failureThreshold: 6
            periodSeconds: 5
            timeoutSeconds: 5
          name: quarkus-petclinic-db
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          resources:
            limits:
              memory: "134217728"
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - quarkus-petclinic-db
        from:
          kind: ImageStreamTag
          name: quarkus-petclinic-db:14
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
